### PR TITLE
keyword extraction using position-biased text ranking 

### PR DESCRIPTION
**Pull request by yalyakoob**
Guy Altman
Madina Izimbetova
Dan Ferber

## Description

Created a feature under nlp.py that uses the position biased text ranking algorithm to extract keywords with the highest probability of having inbound references in the document.  The number of keyword phrases is returned based on descending order of eigenvalue centrality. The function is set to return the top 5 highest keyword phrases. There is the flexibility to return more or less keyword phrases based on preferences. When the keyword extraction function is called into ocr.py it returns a dictionary where the values are pairs of keyword phrases and their eigenvalue centrality score.
Ex:
Keywords: [('DEFENCE WHITEHALL LONDON', 0.16926207243497499), ('Page', 0.14633401874768007), ('MINISTRY', 0.09075843946849015), ('Northern Ireland', 0.08344503557823804), ('Parachute', 0.0773451895826095)]
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by prockwood — APPROVED** [review]
Awesome work guys, addresses the 'too many tags' problem we had earlier, seems like this could be really useful to our users. I need to go read up on eigenvalue centrality.

**Comment by engegreg** [comment]
this is a really good PR. I'd honestly suggest making this a full PR instead of a draft, extremely valuable for both MVP and stretch goals.

**Review by JacksonReber — APPROVED** [review]
This is amazing! Great PR, I think these tags could be valuable and exceed our shareholders expectations

**Review by jhebert1994 — APPROVED** [review]
Great work, we had an issue with spacy using tags too liberally and this is a huge step in limiting those.

**Review by caralocke — CHANGES_REQUESTED** [review]
I'm looking over this and it looks like it was last worked on 5 days ago and is still marked as "a work in progress." Has this been completed?

**Review by bevanger — APPROVED** [review]
Great work, seems to fix a big issue and code looks very clean.

**Comment by dagtag** [comment]
[As a user, I want to be able to see the most prevalent keyword phrases in a document.](https://trello.com/c/BFsUTJbM/100-as-a-user-i-want-to-be-able-to-see-the-most-prevalent-keyword-phrases-in-a-document)

**Review by HeyAnwar — APPROVED** [review]

**Pull request closed without merging**
